from dataclasses import dataclass

@dataclass
class paymentDetails:
    handle: str #//InfinitePay handle, optional to check if the app is logged on expected account
    doc_number: str #// user document number without points, optional to check if the app is logged on expected account
    amount: int #// as int. So 100 represents 1,00 real.
    payment_method: str #// or debit
    installments: int #// if credit
    order_id: int #// And order id generated by your app so you're able to link the transaction with your order.
    result_url: str #// the return deeplink InfinitePay will call when the transaction is finished. Make sure to provide an internal deeplink for a seamless experience.
    app_client_referrer: str #// Your app referrer. Make sure to always provide the same string.
    af_force_deeplink: bool