
class mapUSUARIO:
    def __init__(self, ID_USUARIO, NOME_USUARIO, SENHA_USUARIO, EMAIL_USUARIO, USUARIO_ATIVO, TIPO_USUARIO):
        self.ID_USUARIO = ID_USUARIO
        self.NOME_USUARIO = NOME_USUARIO
        self.SENHA_USUARIO = SENHA_USUARIO
        self.EMAIL_USUARIO = EMAIL_USUARIO
        self.USUARIO_ATIVO = USUARIO_ATIVO
        self.TIPO_USUARIO = TIPO_USUARIO

class mapProduto:
    def __init__(self, ID_PRODUTO, CODIGO_PRODUTO, CODIGO_PRODUTO_PDV, DESCRICAO_PRODUTO, PRECO_BALCAO, PRODUTO_ATIVO, ID_TRIBUTO,
                 CODIGO_ZE):
        self.ID_PRODUTO = ID_PRODUTO
        self.CODIGO_PRODUTO = CODIGO_PRODUTO
        self.CODIGO_PRODUTO_PDV = CODIGO_PRODUTO_PDV
        self.DESCRICAO_PRODUTO = DESCRICAO_PRODUTO
        self.PRECO_BALCAO = PRECO_BALCAO 
        self.PRODUTO_ATIVO = PRODUTO_ATIVO
        self.ID_TRIBUTO = ID_TRIBUTO
        self.CODIGO_ZE = CODIGO_ZE

class mapGradePreco:
    def __init__(self, ID_PRODUTO, QTDE_INICIAL, QTDE_FINAL, PRECO_VENDA) -> None:
        self.ID_PRODUTO = ID_PRODUTO
        self.QTDE_INICIAL = QTDE_INICIAL
        self.QTDE_FINAL = QTDE_FINAL
        self.PRECO_VENDA = PRECO_VENDA

class mapPedido:
    def __init__(self, NUMERO_PEDIDO ,DATA_HORA, DATA_ENTREGA, DATA_HORA_AGENDA ,TEMPO_ENTREGA ,TEMPO_RETIRADA_LOJA ,TEMPO_MOTOBOY_CAMINHO,
                ID_CLIENTE, ID_ENDERECO, CPF, IE ,NOME_CLIENTE ,ENDERECO_CLIENTE ,BAIRRO_CLIENTE ,TELEFONE_CLIENTE ,LATITUDE ,LONGITUDE,
                ORIGEM, ID_CAIXA, STATUS_PEDIDO ,NUMERO_PESSOAS ,NUMERO_VENDA ,TIPO_ADICIONAL ,TOTAL_PRODUTOS ,TROCO ,DESCONTO ,ADICIONAL ,TAXA_ENTREGA,
                TOTAL_PEDIDO ,MOTIVO_DEVOLUCAO ,ID_TRANSPORTE ,INFO_ADICIONAL ,NUMERO_PEDIDO_ZE_DELIVERY ,NUMERO_PEDIDO_DELIVERY ,NUMERO_PEDIDO_LALAMOVE,
                NUMERO_PEDIDO_IFOOD ,ID_PEDIDO_IFOOD, TIPO_PEDIDO_IFOOD ,CODIGO_IDENTIFICACAO_IFOOD ,ORDER_NUMBER_GOOMER ,ID_PEDIDO_GOOMER ,ORDER_NUMBER_WABIZ, 
                INTERNAL_KEY_WABIZ  ,ORDER_NUMBER_RAPPI ,REQUEST_ID_FATTORINO ,INTERNAL_KEY_ZION ,MOTIVO_CANCELAMENTO ,COMENTARIOS_AVALIACAO ,NOTA_AVALIACAO, 
                ORDEM_ROTEIRO ,TEMPO_ATENDIMENTO_ROBO ,TEMPO_ENTREGA_PEDIDO ,ID_PEDIDO_LOCAL ,ID_TERMINAL) -> None:
        
        self.NUMERO_PEDIDO = NUMERO_PEDIDO
        self.DATA_HORA = DATA_HORA
        self.DATA_ENTREGA = DATA_ENTREGA
        self.DATA_HORA_AGENDA = DATA_HORA_AGENDA
        self.TEMPO_ENTREGA = TEMPO_ENTREGA
        self.TEMPO_RETIRADA_LOJA = TEMPO_RETIRADA_LOJA
        self.TEMPO_MOTOBOY_CAMINHO = TEMPO_MOTOBOY_CAMINHO
        self.ID_CLIENTE = ID_CLIENTE
        self.ID_ENDERECO = ID_ENDERECO
        self.CPF = CPF
        self.IE = IE
        self.NOME_CLIENTE = NOME_CLIENTE
        self.ENDERECO_CLIENTE = ENDERECO_CLIENTE
        self.BAIRRO_CLIENTE = BAIRRO_CLIENTE
        self.TELEFONE_CLIENTE = TELEFONE_CLIENTE
        self.LATITUDE = LATITUDE
        self.LONGITUDE = LONGITUDE
        self.ORIGEM = ORIGEM
        self.ID_CAIXA = ID_CAIXA
        self.STATUS_PEDIDO = STATUS_PEDIDO
        self.NUMERO_PESSOAS = NUMERO_PESSOAS
        self.NUMERO_VENDA = NUMERO_VENDA
        self.TIPO_ADICIONAL = TIPO_ADICIONAL
        self.TOTAL_PRODUTOS = TOTAL_PRODUTOS
        self.TROCO = TROCO
        self.DESCONTO = DESCONTO
        self.ADICIONAL = ADICIONAL
        self.TAXA_ENTREGA = TAXA_ENTREGA
        self.TOTAL_PEDIDO = TOTAL_PEDIDO
        self.MOTIVO_DEVOLUCAO = MOTIVO_DEVOLUCAO
        self.ID_TRANSPORTE = ID_TRANSPORTE
        self.INFO_ADICIONAL = INFO_ADICIONAL
        self.NUMERO_PEDIDO_ZE_DELIVERY = NUMERO_PEDIDO_ZE_DELIVERY
        self.NUMERO_PEDIDO_DELIVERY = NUMERO_PEDIDO_DELIVERY
        self.NUMERO_PEDIDO_LALAMOVE = NUMERO_PEDIDO_LALAMOVE
        self.NUMERO_PEDIDO_IFOOD = NUMERO_PEDIDO_IFOOD
        self.ID_PEDIDO_IFOOD = ID_PEDIDO_IFOOD
        self.TIPO_PEDIDO_IFOOD = TIPO_PEDIDO_IFOOD
        self.CODIGO_IDENTIFICACAO_IFOOD = CODIGO_IDENTIFICACAO_IFOOD
        self.ORDER_NUMBER_GOOMER = ORDER_NUMBER_GOOMER
        self.ID_PEDIDO_GOOMER = ID_PEDIDO_GOOMER
        self.ORDER_NUMBER_WABIZ = ORDER_NUMBER_WABIZ
        self.INTERNAL_KEY_WABIZ = INTERNAL_KEY_WABIZ
        self.ORDER_NUMBER_RAPPI = ORDER_NUMBER_RAPPI
        self.REQUEST_ID_FATTORINO = REQUEST_ID_FATTORINO
        self.INTERNAL_KEY_ZION = INTERNAL_KEY_ZION
        self.MOTIVO_CANCELAMENTO = MOTIVO_CANCELAMENTO
        self.COMENTARIOS_AVALIACAO = COMENTARIOS_AVALIACAO
        self.NOTA_AVALIACAO = NOTA_AVALIACAO
        self.ORDEM_ROTEIRO = ORDEM_ROTEIRO
        self.TEMPO_ATENDIMENTO_ROBO = TEMPO_ATENDIMENTO_ROBO
        self.TEMPO_ENTREGA_PEDIDO = TEMPO_ENTREGA_PEDIDO
        self.ID_PEDIDO_LOCAL = ID_PEDIDO_LOCAL
        self.ID_TERMINAL = ID_TERMINAL

class mapItemPedido:
    def __init__(self, NUMERO_ITEM, NUMERO_PEDIDO, ID_PRODUTO, CODIGO_PRODUTO, QTDE, PRECO_UNITARIO, VALOR_TOTAL, ID_TRIBUTO,
                 OBS_ITEM, ID_ITEM_LOCAL, ID_TERMINAL, VALOR_PAGO_STONE) -> None:
        self.NUMERO_ITEM = NUMERO_ITEM
        self.NUMERO_PEDIDO = NUMERO_PEDIDO
        self.ID_PRODUTO = ID_PRODUTO
        self.CODIGO_PRODUTO = CODIGO_PRODUTO
        self.QTDE = QTDE
        self.PRECO_UNITARIO = PRECO_UNITARIO
        self.VALOR_TOTAL =VALOR_TOTAL
        self.ID_TRIBUTO = ID_TRIBUTO
        self.OBS_ITEM = OBS_ITEM
        self.ID_ITEM_LOCAL = ID_ITEM_LOCAL
        self.ID_TERMINAL = ID_TERMINAL
        self.VALOR_PAGO_STONE = VALOR_PAGO_STONE

class mapPedidoPagamento:
    def __init__(self, ID_PAGAMENTO, NUMERO_PEDIDO, DATA_HORA, FORMA_PAGTO, VALOR_PAGO, ID_CAIXA, ORIGEM, ID_PAGAMENTO_LOCAL,
                 ID_TERMINAL, CODIGO_NSU, VALOR_PAGO_STONE, DATA_AUTORIZACAO, BANDEIRA) -> None:
        self.ID_PAGAMENTO = ID_PAGAMENTO
        self.NUMERO_PEDIDO = NUMERO_PEDIDO
        self.DATA_HORA = DATA_HORA
        self.FORMA_PAGTO = FORMA_PAGTO
        self.VALOR_PAGO = VALOR_PAGO
        self.ID_CAIXA = ID_CAIXA
        self.ORIGEM = ORIGEM
        self.ID_PAGAMENTO_LOCAL = ID_PAGAMENTO_LOCAL
        self.ID_TERMINAL = ID_TERMINAL
        self.CODIGO_NSU = CODIGO_NSU
        self.VALOR_PAGO_STONE = VALOR_PAGO_STONE
        self.DATA_AUTORIZACAO = DATA_AUTORIZACAO
        self.BANDEIRA = BANDEIRA

class mapComboProduto:
    def __init__(self, ID_PRODUTO, ID_PRODUTO_COMBO, QTDE_COMBO, PRECO_COMBO):
        self.ID_PRODUTO = ID_PRODUTO
        self.ID_PRODUTO_COMBO = ID_PRODUTO_COMBO
        self.QTDE_COMBO = QTDE_COMBO
        self.PRECO_COMBO = PRECO_COMBO

class mapAssociacaoProduto:
    def __init__(self, ID_ASSOCIACAO, ID_PRODUTO_ESTOQUE, ID_PRODUTO) -> None:
       self. ID_ASSOCIACAO = ID_ASSOCIACAO
       self.ID_PRODUTO_ESTOQUE = ID_PRODUTO_ESTOQUE
       self.ID_PRODUTO = ID_PRODUTO

class mapDoseProduto:
    def __init__(self, ID_PRODUTO_DOSE, ID_PRODUTO, DOSE_ML) -> None:
       self. ID_PRODUTO_DOSE = ID_PRODUTO_DOSE
       self.ID_PRODUTO = ID_PRODUTO
       self.DOSE_ML = DOSE_ML

class mapEstoque:
    def __init__(self, ID_ESTOQUE, DATA_ESTOQUE, ID_PRODUTO, MOVIMENTO, QTDE_ESTOQUE, ID_FORNECEDOR,
                 ID_EMPRESA, SALDO, NUMERO_COMANDA, PRECO_CUSTO, CONTAGEM) -> None:
        self.ID_ESTOQUE = ID_ESTOQUE
        self.DATA_ESTOQUE = DATA_ESTOQUE
        self.ID_PRODUTO = ID_PRODUTO
        self.MOVIMENTO = MOVIMENTO
        self.QTDE_ESTOQUE = QTDE_ESTOQUE
        self.ID_FORNECEDOR = ID_FORNECEDOR
        self.ID_EMPRESA = ID_EMPRESA
        self.SALDO = SALDO
        self.NUMERO_COMANDA = NUMERO_COMANDA
        self.PRECO_CUSTO = PRECO_CUSTO
        self.CONTAGEM = CONTAGEM

class mapFinanceiro:
    def __init__(self,  ID_FINANCEIRO, CREDITO_DEBITO, DATA_LANCAMENTO, DATA_VENCIMENTO, DATA_PAGAMENTO, NUMERO_SEQ_NF_SAIDA, NUMERO_SEQ_NF_ENTRADA,
        VALOR, VALOR_DESCONTO, VALOR_ACRESCIMO, VALOR_TOTAL, HISTORICO, ID_EMPRESA, ID_PLANO, NUMERO_COMANDA, ID_FINANCEIRO_LOCAL,
        ID_TERMINAL) -> None:
        self.ID_FINANCEIRO = ID_FINANCEIRO
        self.CREDITO_DEBITO = CREDITO_DEBITO
        self.DATA_LANCAMENTO = DATA_LANCAMENTO
        self.DATA_VENCIMENTO = DATA_VENCIMENTO
        self.DATA_PAGAMENTO = DATA_PAGAMENTO
        self.NUMERO_SEQ_NF_SAIDA = NUMERO_SEQ_NF_SAIDA
        self.NUMERO_SEQ_NF_ENTRADA = NUMERO_SEQ_NF_ENTRADA
        self.VALOR = VALOR
        self.VALOR_DESCONTO = VALOR_DESCONTO
        self.VALOR_ACRESCIMO = VALOR_ACRESCIMO
        self.VALOR_TOTAL = VALOR_TOTAL
        self.HISTORICO = HISTORICO
        self.ID_EMPRESA = ID_EMPRESA
        self.ID_PLANO = ID_PLANO
        self.NUMERO_COMANDA = NUMERO_COMANDA
        self.ID_FINANCEIRO_LOCAL = ID_FINANCEIRO_LOCAL
        self.ID_TERMINAL = ID_TERMINAL

class mapFormaPagto:
    def __init__(self, ID_FORMA, DESCRICAO_FORMA, PAGTO_FUTURO, VALE_FUNCIONARIO, VALOR_DIA, TAXA_PAGAMENTO, 
            DIAS_PAGAMENTO) -> None:
        self.ID_FORMA = ID_FORMA 
        self.DESCRICAO_FORMA = DESCRICAO_FORMA, 
        self.PAGTO_FUTURO = PAGTO_FUTURO 
        self.VALE_FUNCIONARIO = VALE_FUNCIONARIO 
        self.VALOR_DIA = VALOR_DIA
        self.TAXA_PAGAMENTO = TAXA_PAGAMENTO
        self.DIAS_PAGAMENTO = DIAS_PAGAMENTO

class mapPlanoConta:
    def __init__(self, ID_PLANO, DESCRICAO_PLANO, CREDITO_DEBITO, PAI_PLANO) -> None:
        self.ID_PLANO = ID_PLANO
        self.DESCRICAO_PLANO = DESCRICAO_PLANO
        self.CREDITO_DEBITO = CREDITO_DEBITO
        self.PAI_PLANO = PAI_PLANO

class mapAtendimentoComanda:
    def __init__(self, ID_ATENDIMENTO, NUMERO_COMANDA_ATENDIMENTO, ID_PRODUTO, QTDE, PRECO, NUMERO_COMANDA, FECHADO,
            DATA_HORA, ID_TRIBUTO, MESA, OBS_ITEM, IMPRESSAO, AGRUPADOR, IMPRESSAO_PRECONTA, DESCONTO, ADICIONAL,
            DESCRICAO_PRODUTO, QTDE_IMPRESSAO, ID_ATENDIMENTO_LOCAL, ID_TERMINAL, NOME_MESA) -> None:
        self.ID_ATENDIMENTO = ID_ATENDIMENTO
        self.NUMERO_COMANDA_ATENDIMENTO = NUMERO_COMANDA_ATENDIMENTO
        self.ID_PRODUTO = ID_PRODUTO
        self.QTDE = QTDE
        self.PRECO = PRECO
        self.NUMERO_COMANDA = NUMERO_COMANDA 
        self.FECHADO = FECHADO
        self.DATA_HORA = DATA_HORA
        self.ID_TRIBUTO = ID_TRIBUTO
        self.MESA = MESA
        self.OBS_ITEM = OBS_ITEM 
        self.IMPRESSAO = IMPRESSAO
        self.AGRUPADOR = AGRUPADOR
        self.IMPRESSAO_PRECONTA = IMPRESSAO_PRECONTA 
        self.DESCONTO = DESCONTO
        self.ADICIONAL = ADICIONAL
        self.DESCRICAO_PRODUTO = DESCRICAO_PRODUTO
        self.QTDE_IMPRESSAO = QTDE_IMPRESSAO
        self.ID_ATENDIMENTO_LOCAL = ID_ATENDIMENTO_LOCAL
        self.ID_TERMINAL = ID_TERMINAL
        self.NOME_MESA = NOME_MESA

class mapAberturaCaixa:
    def __init__(self, ID_ABERTURA, ID_EMPRESA, DATA_ABERTURA, VALOR_ABERTURA, VALOR_FECHAMENTO, 
        ID_USUARIO, DATA_FECHAMENTO, IMPRESSAO):
        self.ID_ABERTURA = ID_ABERTURA
        self.ID_EMPRESA = ID_EMPRESA
        self.DATA_ABERTURA = DATA_ABERTURA
        self.VALOR_ABERTURA = VALOR_ABERTURA
        self.VALOR_FECHAMENTO = VALOR_FECHAMENTO
        self.ID_USUARIO = ID_USUARIO
        self.DATA_FECHAMENTO = DATA_FECHAMENTO,
        self.IMPRESSAO = IMPRESSAO

class mapFechamentoCaixa:
    def __init__(self, ID_FECHAMENTO, ID_ABERTURA, FORMA_PAGTO, VALOR_FECHAMENTO, DATA_FECHAMENTO, DIFERENCA, 
                 ID_FECHAMENTO_LOCAL, ID_TERMINAL):
        
        self.ID_FECHAMENTO = ID_FECHAMENTO
        self.ID_ABERTURA = ID_ABERTURA
        self.FORMA_PAGTO = FORMA_PAGTO
        self.VALOR_FECHAMENTO = VALOR_FECHAMENTO
        self.DATA_FECHAMENTO = DATA_FECHAMENTO
        self.DIFERENCA = DIFERENCA
        self.ID_FECHAMENTO_LOCAL = ID_FECHAMENTO_LOCAL
        self.ID_TERMINAL = ID_TERMINAL

class mapCliente:
    def __init__(self, ID_CLIENTE, NOME_CLIENTE, CPF, ENDERECO_CLIENTE, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO,
                 BAIRRO_CLIENTE, CEP_CLIENTE, MUNICIPIO_CLIENTE, UF_CLIENTE, TELEFONE_CLIENTE, EMAIL_CLIENTE, ID_EMPRESA,
                 IE, BLACK_LIST, NOME_FANTASIA_CLIENTE, OBS_CLIENTE, TAXA_ENTREGA) -> None:
        self.ID_CLIENTE = ID_CLIENTE
        self.NOME_CLIENTE = NOME_CLIENTE
        self.CPF = CPF
        self.ENDERECO_CLIENTE = ENDERECO_CLIENTE
        self.NUMERO_ENDERECO = NUMERO_ENDERECO
        self.COMPLEMENTO_ENDERECO = COMPLEMENTO_ENDERECO
        self.BAIRRO_CLIENTE = BAIRRO_CLIENTE
        self.CEP_CLIENTE = CEP_CLIENTE
        self.MUNICIPIO_CLIENTE = MUNICIPIO_CLIENTE
        self.UF_CLIENTE = UF_CLIENTE
        self.TELEFONE_CLIENTE = TELEFONE_CLIENTE
        self.EMAIL_CLIENTE = EMAIL_CLIENTE
        self.ID_EMPRESA = ID_EMPRESA
        self.IE = IE
        self.BLACK_LIST = BLACK_LIST
        self.NOME_FANTASIA_CLIENTE = NOME_FANTASIA_CLIENTE
        self.OBS_CLIENTE = OBS_CLIENTE
        self.TAXA_ENTREGA = TAXA_ENTREGA

class mapEnderecoCliente:
    def __init__(self, ID_ENDERECO, ID_CLIENTE, ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, BAIRRO, CEP,
                 MUNICIPIO, UF, ID_EMPRESA, LATITUDE, LONGITUDE) -> None:
        self.ID_ENDERECO = ID_ENDERECO
        self.ID_CLIENTE = ID_CLIENTE
        self.ENDERECO = ENDERECO
        self.NUMERO_ENDERECO = NUMERO_ENDERECO
        self.COMPLEMENTO_ENDERECO = COMPLEMENTO_ENDERECO
        self.BAIRRO = BAIRRO
        self.CEP = CEP
        self.MUNICIPIO = MUNICIPIO
        self.UF = UF
        self.ID_EMPRESA = ID_EMPRESA
        self.LATITUDE = LATITUDE
        self.LONGITUDE = LONGITUDE

class mapTransporte:
    def __init__(self, ID_TRANSPORTE, NOME_TRANSPORTE, CNPJ, IE, ENDERECO, CIDADE, UF, PLACA, EMAIL) -> None:
        self.ID_TRANSPORTE = ID_TRANSPORTE
        self.NOME_TRANSPORTE = NOME_TRANSPORTE
        self.CNPJ = CNPJ
        self.IE = IE
        self.ENDERECO = ENDERECO
        self.CIDADE = CIDADE
        self.UF = UF
        self.PLACA = PLACA
        self.EMAIL = EMAIL

class mapFilaComanda:
    def __init__(self, ID_FILA, NUMERO_COMANDA, PROCESSADO) -> None:
        self.ID_FILA = ID_FILA
        self.NUMERO_COMANDA = NUMERO_COMANDA
        self.PROCESSADO = PROCESSADO

class mapPedidoNFe:
    def __init__(self, ID_PEDIDO_NFE, NUMERO_PEDIDO, XML_NOTA, RESPOSTA_SEFAZ, NUMERO_NF, SERIE_NF,
                CHAVE_ACESSO_NF, PROTOCOLO_AUTORIZACAO, PROCESSADO, ASSINATURA_NFCE,
                DATA_AUTORIZACAO_NFCE, CHAVE_PEDIDO, XML_DEVOLUCAO, NUMERO_NF_DEVOLUCAO,
                GERAR_DANFE, ID_EMPRESA, CHAVE_NF_DEVOLUCAO, ID_PEDIDO_NFE_LOCAL, ID_TERMINAL):
        self.ID_PEDIDO_NFE =  ID_PEDIDO_NFE
        self.NUMERO_PEDIDO =  NUMERO_PEDIDO
        self.XML_NOTA =  XML_NOTA
        self.RESPOSTA_SEFAZ =  RESPOSTA_SEFAZ
        self.NUMERO_NF =  NUMERO_NF
        self.SERIE_NF = SERIE_NF
        self.CHAVE_ACESSO_NF =  CHAVE_ACESSO_NF
        self.PROTOCOLO_AUTORIZACAO =  PROTOCOLO_AUTORIZACAO
        self.PROCESSADO =  PROCESSADO
        self.ASSINATURA_NFCE = ASSINATURA_NFCE
        self.DATA_AUTORIZACAO_NFCE = DATA_AUTORIZACAO_NFCE
        self.CHAVE_PEDIDO = CHAVE_PEDIDO
        self.XML_DEVOLUCAO = XML_DEVOLUCAO
        self.NUMERO_NF_DEVOLUCAO = NUMERO_NF_DEVOLUCAO
        self.GERAR_DANFE = GERAR_DANFE
        self.ID_EMPRESA = ID_EMPRESA
        self.CHAVE_NF_DEVOLUCAO = CHAVE_NF_DEVOLUCAO
        self.ID_PEDIDO_NFE_LOCAL = ID_PEDIDO_NFE_LOCAL
        self.ID_TERMINAL = ID_TERMINAL

class mapEmpresa:
    def __init__(self, ID_EMPRESA, NOME_FANTASIA, RAZAO_SOCIAL, CNPJ, NUMERO_NFCE, SERIE_NFCE, ENDERECO, TELEFONE, CLIENT_ID_IFOOD, CLIENT_SECRET_IFOOD, 
        GRANT_TYPE_IFOOD, MERCHANT_ID_IFOOD, MAQUINA_IMPRESSAO, EMAIL_LOGIN_ZE, SENHA_LOGIN_ZE, VIAS_IMPRESSAO,
        IE, BAIRRO, CEP, CIDADE, UF, SERIAL_PROTOCOLO, CODIGO_MUNICIPIO_IBGE, CRT, FATURAR_TAXA_ENTREGA):
        
        self.ID_EMPRESA = ID_EMPRESA
        self.NOME_FANTASIA = NOME_FANTASIA
        self.RAZAO_SOCIAL = RAZAO_SOCIAL
        self.CNPJ = CNPJ
        self.NUMERO_NFCE = NUMERO_NFCE
        self.SERIE_NFCE = SERIE_NFCE
        self.ENDERECO = ENDERECO
        self.TELEFONE  = TELEFONE
        self.CLIENT_ID_IFOOD = CLIENT_ID_IFOOD
        self.CLIENT_SECRET_IFOOD = CLIENT_SECRET_IFOOD
        self.GRANT_TYPE_IFOOD = GRANT_TYPE_IFOOD
        self.MERCHANT_ID_IFOOD = MERCHANT_ID_IFOOD
        self.MAQUINA_IMPRESSAO = MAQUINA_IMPRESSAO
        self.EMAIL_LOGIN_ZE = EMAIL_LOGIN_ZE
        self.SENHA_LOGIN_ZE = SENHA_LOGIN_ZE
        self.VIAS_IMPRESSAO = VIAS_IMPRESSAO
        self.IE = IE
        self.BAIRRO = BAIRRO 
        self.CEP = CEP 
        self.CIDADE = CIDADE
        self.UF = UF
        self.SERIAL_PROTOCOLO = SERIAL_PROTOCOLO
        self.CODIGO_MUNICIPIO_IBGE = CODIGO_MUNICIPIO_IBGE
        self.CRT = CRT
        self.FATURAR_TAXA_ENTREGA = FATURAR_TAXA_ENTREGA

class mapSangria:
    def __init__(self, ID_SANGRIA, DATA_SANGRIA, DESCRICAO_SANGRIA, ID_USUARIO, VALOR_SANGRIA, ID_SANGRIA_LOCAL,
            ID_TERMINAL, ID_ABERTURA):

        self.ID_SANGRIA = ID_SANGRIA
        self.DATA_SANGRIA = DATA_SANGRIA
        self.DESCRICAO_SANGRIA = DESCRICAO_SANGRIA
        self.ID_USUARIO = ID_USUARIO
        self.VALOR_SANGRIA = VALOR_SANGRIA
        self.ID_SANGRIA_LOCAL = ID_SANGRIA_LOCAL
        self.ID_TERMINAL = ID_TERMINAL
        self.ID_ABERTURA = ID_ABERTURA

class mapReforco:
    def __init__(self, ID_REFORCO, DATA_REFORCO, ID_USUARIO, VALOR_REFORCO, ID_REFORCO_LOCAL, ID_TERMINAL, ID_ABERTURA):
        self.ID_REFORCO  = ID_REFORCO
        self.DATA_REFORCO = DATA_REFORCO 
        self.ID_USUARIO = ID_USUARIO
        self.VALOR_REFORCO = VALOR_REFORCO
        self.ID_REFORCO_LOCAL = ID_REFORCO_LOCAL
        self.ID_TERMINAL = ID_TERMINAL
        self.ID_ABERTURA  = ID_ABERTURA

class mapMunicipio:
    def __init__(self, ID_IBGE, ID_UF, ID_MUNICIPIO, NOME_MUNICIPIO, SIGLA_UF):
        self.ID_IBGE = ID_IBGE 
        self.ID_UF = ID_UF
        self.ID_MUNICIPIO = ID_MUNICIPIO
        self.NOME_MUNICIPIO = NOME_MUNICIPIO
        self.SIGLA_UF = SIGLA_UF

class mapCodigoBarrasProduto:
    def __init__(self, ID_BARRAS, ID_PRODUTO, CODIGO_BARRAS_PRODUTO):
        self.ID_BARRAS = ID_BARRAS
        self.ID_PRODUTO = ID_PRODUTO
        self.CODIGO_BARRAS_PRODUTO = CODIGO_BARRAS_PRODUTO

class mapTributo:
    def __init__(self, ID_TRIBUTO, NCM, UF_DESTINO, CFOP, CST, ALIQ_ICMS, ALIQ_INTERNA_ICMS, MODO_BASE_CALCULO_ICMS_ST,  
        IVA, CST_IPI, ALIQ_IPI, CST_PIS, ALIQ_PIS, CST_COFINS, ALIQ_COFINS, NOME_OPERACAO, CEST, PERCENTUAL_RED_BASE_ICMS,  
        CODIGO_GENERO, ID_EMPRESA, PERCENTUAL_FCP):
        self.ID_TRIBUTO = ID_TRIBUTO
        self.NCM  = NCM
        self.UF_DESTINO = UF_DESTINO
        self.CFOP = CFOP
        self.CST = CST
        self.ALIQ_ICMS = ALIQ_ICMS 
        self.ALIQ_INTERNA_ICMS = ALIQ_INTERNA_ICMS
        self.MODO_BASE_CALCULO_ICMS_ST = MODO_BASE_CALCULO_ICMS_ST
        self.IVA = IVA
        self.CST_IPI = CST_IPI
        self.ALIQ_IPI = ALIQ_IPI
        self.CST_PIS = CST_PIS
        self.ALIQ_PIS = ALIQ_PIS
        self.CST_COFINS = CST_COFINS
        self.ALIQ_COFINS = ALIQ_COFINS
        self.NOME_OPERACAO = NOME_OPERACAO
        self.CEST = CEST
        self.PERCENTUAL_RED_BASE_ICMS = PERCENTUAL_RED_BASE_ICMS 
        self.CODIGO_GENERO = CODIGO_GENERO
        self.ID_EMPRESA = ID_EMPRESA
        self.PERCENTUAL_FCP = PERCENTUAL_FCP

class mapCFOP:
    def __init__(self, CFOP, DESCRICAO_CFOP, VENDA, DEVOLUCAO):
        self.CFOP = CFOP
        self.DESCRICAO_CFOP = DESCRICAO_CFOP
        self.VENDA = VENDA
        self.DEVOLUCAO = DEVOLUCAO

class mapMESA:
    def __init__(self, ID_MESA, NUMERO_MESA, NOME_MESA, MESA_FECHADA, NUMERO_PEDIDO):
        self.ID_MESA = ID_MESA 
        self.NUMERO_MESA = NUMERO_MESA
        self.NOME_MESA = NOME_MESA
        self.MESA_FECHADA = MESA_FECHADA
        self.NUMERO_PEDIDO = NUMERO_PEDIDO
