create table tb_fechamento_caixa (
	ID_FECHAMENTO bigint auto_increment not null,
    ID_ABERTURA bigint,
    FORMA_PAGTO varchar(30),
    VALOR_FECHAMENTO numeric(18,11),
    DATA_FECHAMENTO datetime,
    DIFERENCA numeric(18,11),
    ID_FECHAMENTO_LOCAL bigint,
    ID_TERMINAL int,
    PRIMARY KEY (ID_FECHAMENTO),
    KEY IDX_ID_ABERTURA1 (ID_ABERTURA)
);

CREATE TABLE enderecos (
   id int NOT NULL AUTO_INCREMENT,
   cep varchar(11) NOT NULL,
   uf varchar(2) DEFAULT NULL,
   cidade varchar(120) DEFAULT NULL,
   bairro varchar(120) DEFAULT NULL,
   logradouro varchar(255) DEFAULT NULL,
   latitude varchar(30) DEFAULT NULL,
   longitude varchar(30) DEFAULT NULL,
   ibge_cod_uf varchar(5) DEFAULT NULL,
   ibge_cod_cidade varchar(10) DEFAULT NULL,
   area_cidade_km2 varchar(20) DEFAULT NULL,
   ddd int(3) DEFAULT NULL,
   ativo int(1) DEFAULT NULL,
   PRIMARY KEY (id),
   UNIQUE KEY cep (cep),
   KEY IDX_LOGRADOURO (logradouro),
   KEY IDX_MUN1 (uf, cidade, logradouro)
);

create table tb_coletor (
ID_COLETOR BIGINT NOT NULL AUTO_INCREMENT,
ID_LOJA int,
URL_LOJA varchar(100),
primary key(ID_COLETOR)
);

CREATE TABLE TB_EMPRESA
(ID_EMPRESA INT NOT NULL AUTO_INCREMENT,
NOME_FANTASIA VARCHAR(30),
RAZAO_SOCIAL VARCHAR(80),
CNPJ VARCHAR(20),
IE VARCHAR(15),
ENDERECO VARCHAR(80),
CEP VARCHAR(10),
CIDADE VARCHAR(60),
UF VARCHAR(2),
TELEFONE VARCHAR(15),
WHATSAPP VARCHAR(15),
EMAIL VARCHAR(80),
EMPRESA_ATIVA NUMERIC(1),
SENHA VARCHAR(200),
LATITUDE numeric(18, 11),
LONGITUDE numeric(18, 11),
HORA_INICIAL varchar(5),
HORA_FINAL varchar(5),
CONTATO varchar(80) DEFAULT NULL,
NUMERO_NF decimal(18,0) DEFAULT NULL,
SERIE_NF varchar(10) DEFAULT NULL,
NOME_CERTIFICADO varchar(300) DEFAULT NULL,
VALIDADE_CERTIFICADO datetime DEFAULT NULL,
SERIAL_PROTOCOLO varchar(25) DEFAULT NULL,
BAIRRO varchar(60) DEFAULT NULL,
EMAIL_LOGIN_ZE varchar(100),
SENHA_LOGIN_ZE varchar(100),
URL_ZION varchar(100),
LOGIN_IFOOD varchar(100),
SENHA_IFOOD varchar(100),
NUMERO_CAIXA varchar(10),
MODELO_EQUIPAMENTO_SAT varchar(100),
ASSINATURA_SAT longtext, 
CODIGO_ATIVACAO_SAT varchar(32),
NUMERO_SERIE_CERTIFICADO_ZION varchar(50),
ULTIMO_PING_ROBO datetime,
LOJA_ABERTA numeric(1),
LOGIN_LALAMOVE varchar(100),
SENHA_LALAMOVE varchar(100),
GRANT_TYPE_IFOOD varchar(100),
CLIENT_ID_IFOOD varchar(100),
CLIENT_SECRET_IFOOD varchar(200),
MERCHANT_ID_IFOOD varchar(150),
CHAVE_API_GOOGLE varchar(150),
MAQUINA_IMPRESSAO int,
NUMERO_NFCE numeric(18), 
SERIE_NFCE varchar(10),
AUTHTOKEN_GOOMER varchar(200),
REFRESHTOKEN_GOOMER varchar(200),
STORE_ID_GOOMER varchar(25),
CLIENT_SECRET_GOOMER varchar(250),
CLIENT_ID_GOOMER varchar(250),
VERSAO_LAYOUT_SAT varchar(5),
CHAVE_FLEXDOCS varchar(250),
CODIGO_MUNICIPIO_IBGE varchar(8),
CRT varchar(1),
MODELO_XML varchar(3),
SEM_IMPRESSAO_PEDIDO varchar(1),
IMPRESSORA varchar(55),
DRIVER_IMPRESSORA varchar(10),
VIAS_IMPRESSAO varchar(1),
TIPO_IMPRESSORA varchar(25),
TOKEN_CSC varchar(6), 
CSC varchar(100), 
ID_LOJA_REDECARD varchar(15),
LOGIN_REDECARD varchar(100),
SENHA_REDECARD varchar(100),
FATURAR_TAXA_ENTREGA int,
AUTHTOKEN_WABIZ varchar(500),
LOGIN_WABIZ varchar(100),
SENHA_WABIZ varchar(100),
LOGIN_RAPPI varchar(100), 
SENHA_RAPPI varchar(100),
LOGIN_GO2GO varchar(100), 
SENHA_GO2GO varchar(100),
VALOR_BASE_ENTREGA numeric(12,2),
INSTITUTION_ID_FATTORINO int,
API_KEY_FATTORINO varchar(100),
URL_WOO varchar(100),
CONSUMER_KEY_WOO varchar(100),
CONSUMER_SECRET_WOO varchar(100),
MODELO_IMPRESSAO_ETIQUETA varchar(3000),
URL_ANOTAAI varchar(150), 
ID_LOJA_ANOTAAI varchar(150), 
TOKEN_ANOTAAI varchar(500),
VERSAO_PDV varchar(5),
TOKEN_STONE varchar(100),
REFERENCE_STONE varchar(100),
PRIMARY KEY (ID_EMPRESA));

CREATE TABLE tb_cliente (
 ID_CLIENTE int(11) NOT NULL AUTO_INCREMENT,
 NOME_CLIENTE varchar(120) DEFAULT NULL,
 ENDERECO_CLIENTE varchar(200) DEFAULT NULL,
 NUMERO_ENDERECO varchar(12) DEFAULT NULL,
 COMPLEMENTO_ENDERECO varchar(50) DEFAULT NULL,
 BAIRRO_CLIENTE varchar(150) DEFAULT NULL,
 CEP_CLIENTE varchar(10) DEFAULT NULL,
 MUNICIPIO_CLIENTE varchar(80) DEFAULT NULL,
 UF_CLIENTE varchar(2) DEFAULT NULL,
 TELEFONE_CLIENTE varchar(20) DEFAULT NULL,
 EMAIL_CLIENTE varchar(120) DEFAULT NULL,
 ID_EMPRESA int(11) DEFAULT NULL,
 SENHA_CLIENTE varchar(250) DEFAULT NULL,
 NICKNAME varchar(50) DEFAULT NULL,
 METADE decimal(1,0) DEFAULT NULL,
 UM_TERCO decimal(1,0) DEFAULT NULL,
 CPF varchar(15) DEFAULT NULL,
 IE varchar(15) DEFAULT NULL,
 BLACK_LIST numeric(1),
 NOME_FANTASIA_CLIENTE varchar(35),
 OBS_CLIENTE varchar(400),
 TAXA_ENTREGA numeric(12,2),
 ID_CLIENTE_LOCAL int,
 ID_TERMINAL int,
 PRIMARY KEY (ID_CLIENTE),
 KEY TB_EMPRESA_FK6 (ID_EMPRESA),
 KEY IDX_TELEFONE (TELEFONE_CLIENTE),
 KEY IDX_NOME1 (NOME_CLIENTE),
 KEY IDX_CPF (CPF),
 CONSTRAINT TB_EMPRESA_FK6 FOREIGN KEY (ID_EMPRESA) REFERENCES tb_empresa(ID_EMPRESA)
 );

CREATE TABLE tb_familia_produto (
   ID_FAMILIA int(11) NOT NULL AUTO_INCREMENT,
   DESCRICAO_FAMILIA varchar(60) DEFAULT NULL,
   ID_EMPRESA INT,
   ICONE varchar(50),
   TAMANHO_PIZZA varchar(1),
   PREPARO_COZINHA int,
   PRIMARY KEY (ID_FAMILIA),
   CONSTRAINT TB_EMPRESA_FK3 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA)
 );

 CREATE TABLE tb_produto (
   ID_PRODUTO bigint(20) NOT NULL AUTO_INCREMENT,
   CODIGO_PRODUTO varchar(25) DEFAULT NULL,
   DESCRICAO_PRODUTO varchar(150) DEFAULT NULL,
   PRECO_VENDA decimal(18,2) DEFAULT NULL,
   ID_FAMILIA int(11) DEFAULT NULL,
   ID_EMPRESA INT,
   FOTO_PRODUTO LONGBLOB,
   FOTO2_PRODUTO LONGBLOB,
   PRODUTO_ATIVO INT,
   PRECO_CUSTO decimal(18,2) DEFAULT NULL,
   ARQUIVO_FOTO varchar(120), 
   ARQUIVO2_FOTO varchar(120), 
   ORDEM_RELEVANCIA decimal(10,0),
   NCM varchar(10) DEFAULT NULL,
   CFOP varchar(5) DEFAULT NULL,
   CODIGO_ZE_DELIVERY bigint(20) DEFAULT NULL,
   METADE numeric(1),
   UM_TERCO numeric(1),
   DESCRICAO_ESTOQUE_ZE varchar(250),
   CODIGO_PRODUTO_PDV varchar(25),
   PRECO_ATACADO decimal(18,2) DEFAULT NULL,
   PRECO_BALCAO decimal(18,2),
   PRECO_DELIVERY decimal(18,2),
   ESTOQUE_MINIMO decimal(18,2),
   ID_TRIBUTO bigint,
   CODIGO_IFOOD varchar(20),
   CODIGO_GOOMER varchar(20),
   CODIGO_WABIZ varchar(20),
   DOSE_ML numeric(12,2),
   DESCRICAO_DETALHADA varchar(500),
   SKU varchar(25),
   CODIGO_WOO varchar(25),
   MARKUP numeric(6,2),
   CODIGO_ZE varchar(20),
   CODIGO_ANOTAAI varchar(20),
   PRIMARY KEY (ID_PRODUTO),
   CONSTRAINT TB_EMPRESA_FK7 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA),
   KEY IDX_NOME_PRODUTO (DESCRICAO_PRODUTO),
   KEY IDX_FAMILIA (ID_FAMILIA),
   KEY IDX_PRODUTO_ANOTAAI (CODIGO_ANOTAAI),
   CONSTRAINT tb_produto_ibfk_1 FOREIGN KEY (ID_FAMILIA) REFERENCES tb_familia_produto (ID_FAMILIA)
 );

create table tb_dose_produto (
ID_PRODUTO_DOSE bigint(20) NOT NULL,
ID_PRODUTO  bigint(20) NOT NULL,
DOSE_ML numeric(12, 3),
PRIMARY KEY (ID_PRODUTO_DOSE, ID_PRODUTO)
);

create table tb_materia_prima (
ID_MATERIA_PRIMA bigint(20) NOT NULL auto_increment,
CODIGO_MATERIA_PRIMA varchar(25),
DESCRICAO_MATERIA_PRIMA varchar(180),
PRIMARY KEY (ID_MATERIA_PRIMA)
);

create table tb_ficha_tecnica (
ID_FICHA_TECNICA bigint(20) NOT NULL auto_increment,
ID_PRODUTO bigint(20),
ID_MATERIA_PRIMA bigint(20),
QTDE_MATERIA_PRIMA numeric(18, 3),
CUSTO_MATERIA_PRIMA numeric(18, 2),
QTDE_BRUTA_MATERIA_PRIMA numeric(18, 3),
RECEITA longtext,
PRIMARY KEY (ID_FICHA_TECNICA)
);

create table tb_associacao_produto(
ID_ASSOCIACAO bigint auto_increment not null,
ID_PRODUTO_ESTOQUE bigint,
ID_PRODUTO bigint,
KEY IDX_PRODUTO_ESTOQUE (ID_PRODUTO_ESTOQUE),
PRIMARY KEY (ID_ASSOCIACAO)
);

create table TB_GRADE_PRODUTO (
   ID_PRODUTO bigint not null,
   QTDE_INICIAL int not null,
   QTDE_FINAL int not null,
   PRECO_VENDA numeric(18,2),
   CONSTRAINT TB_PRODUTO_FKG FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
   PRIMARY KEY (ID_PRODUTO, QTDE_INICIAL, QTDE_FINAL)
); 

CREATE TABLE tb_fornecedor (
   ID_FORNECEDOR int(11) NOT NULL AUTO_INCREMENT,
   NOME_FANTASIA varchar(30) DEFAULT NULL,
   RAZAO_SOCIAL varchar(80) DEFAULT NULL,
   CNPJ_FORNECEDOR varchar(20) DEFAULT NULL,
   IE_FORNECEDOR varchar(15) DEFAULT NULL,
   ENDERECO varchar(80) DEFAULT NULL,
   NUMERO_ENDERECO varchar(10) DEFAULT NULL,
   COMPLEMENTO_ENDERECO varchar(20) DEFAULT NULL,
   CEP_FORNECEDOR varchar(10) DEFAULT NULL,
   CIDADE_FORNECEDOR varchar(60) DEFAULT NULL,
   UF_FORNECEDOR varchar(2) DEFAULT NULL,
   TELEFONE_FORNECEDOR varchar(15) DEFAULT NULL,
   EMAIL_FORNECEDOR varchar(80) DEFAULT NULL,
   WHATSAPP varchar(15) DEFAULT NULL,
   ID_EMPRESA INT,
   CONSTRAINT TB_EMPRESA_FK4 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA),
   PRIMARY KEY (ID_FORNECEDOR)
 );

CREATE TABLE tb_usuario (
   ID_USUARIO int(11) NOT NULL AUTO_INCREMENT,
   EMAIL_USUARIO varchar(120) DEFAULT NULL,
   SENHA_USUARIO varchar(250) DEFAULT NULL,
   NOME_USUARIO varchar(80) DEFAULT NULL,
   USUARIO_ATIVO decimal(1,0) DEFAULT NULL,
   TIPO_USUARIO int(11) DEFAULT NULL,
   ID_EMPRESA INT,
   ACESSO_FECHAMENTO int,
   USUARIO_CAIXA int,
   TELA_INICIAL int,
   CAIXA_DELIVERY int,
   CONSTRAINT TB_EMPRESA_FK8 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA),
   PRIMARY KEY (ID_USUARIO),
   KEY IDX_EMAIL (EMAIL_USUARIO)
);

CREATE TABLE tb_historico_login (
   ID_LOGIN bigint(20) NOT NULL AUTO_INCREMENT,
   DATA_HORA datetime DEFAULT NULL,
   IP_ADDRESS varchar(15) DEFAULT NULL,
   EMAIL varchar(150) DEFAULT NULL,
   PRIMARY KEY (ID_LOGIN),
   KEY IDX_EMAIL_HISTORICO (EMAIL,DATA_HORA)
);

CREATE TABLE tb_estoque (
   ID_ESTOQUE bigint(20) NOT NULL AUTO_INCREMENT,
   DATA_ESTOQUE datetime DEFAULT NULL,
   ID_PRODUTO bigint(20) DEFAULT NULL,
   MOVIMENTO int(11) DEFAULT NULL,
   QTDE_ESTOQUE decimal(18,3) DEFAULT NULL,
   ID_FORNECEDOR int(11) DEFAULT NULL,
   ID_EMPRESA INT,
   SALDO decimal(18,3) DEFAULT NULL,
   NUMERO_COMANDA BIGINT,
   PRECO_CUSTO decimal (18,11),
   CONTAGEM int,
   PRIMARY KEY (ID_ESTOQUE),
   KEY ID_FORNECEDOR (ID_FORNECEDOR),
   KEY IDX_DATA_PRODUTO (ID_PRODUTO,DATA_ESTOQUE),
   CONSTRAINT tb_estoque_ibfk_2 FOREIGN KEY (ID_PRODUTO) REFERENCES tb_produto (ID_PRODUTO),
   CONSTRAINT TB_EMPRESA_FK11 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA)
 );
 
CREATE TABLE TB_PROMOCAO (
	ID_PROMOCAO BIGINT NOT NULL AUTO_INCREMENT,
	DATA_PROMOCAO DATETIME, 
	DATA_VALIDADE DATETIME,
	ID_CLIENTE INT, 
	ID_PRODUTO BIGINT,
	PRECO_PROMOCAO decimal(18,2),
	FOTO_PROMOCAO BLOB,
	ID_EMPRESA int,
    TEXTO_PROMOCAO varchar(600),
	PRIMARY KEY (ID_PROMOCAO),
	KEY IDX_DATA_PROMOCAO (DATA_PROMOCAO),
	KEY IDX_DATA_VALIDADE (DATA_VALIDADE),
	KEY IDX_PRODUTO_VALIDADE (ID_PRODUTO, DATA_VALIDADE),
	KEY IDX_ID_CLIENTE_DATA_VALIDADE (ID_CLIENTE, DATA_VALIDADE),
	CONSTRAINT TB_EMPRESA_FK22 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA),
	CONSTRAINT TB_PRODUTO_FK22 FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
	CONSTRAINT TB_CLIENTE_FK22 FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
);

CREATE TABLE TB_ENDERECO_CLIENTE (
    ID_ENDERECO BIGINT auto_increment NOT NULL,
    ID_CLIENTE INT,
    ENDERECO varchar(200) DEFAULT NULL,
    NUMERO_ENDERECO varchar(12) DEFAULT NULL,
    COMPLEMENTO_ENDERECO varchar(50) DEFAULT NULL,
    BAIRRO varchar(150) DEFAULT NULL,
    CEP varchar(10) DEFAULT NULL,
    MUNICIPIO varchar(80) DEFAULT NULL,
    UF varchar(2) DEFAULT NULL,
    ID_EMPRESA int DEFAULT NULL,
    LATITUDE numeric(18, 11),
    LONGITUDE numeric(18, 11),
    ID_ENDERECO_LOCAL BIGINT,
	ID_TERMINAL int,
    PRIMARY KEY (ID_ENDERECO),
    KEY IDX_CLIENTE_ENDERECO (ID_CLIENTE),
	KEY IDX_ID_CLIENTE_CEP (ID_CLIENTE, CEP),
    constraint TB_CLIENTE_E21 FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    constraint TB_EMPRESA_E21 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE TB_FRETE (
	ID_FRETE INT NOT NULL AUTO_INCREMENT,
    DISTANCIA NUMERIC(10,2),
    VALOR NUMERIC(18,2),
    ID_EMPRESA int,
    PRIMARY KEY (ID_FRETE),
    KEY IDX_FRETE_DISTANCIA (DISTANCIA),
    constraint TB_EMPRESA_E22 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

CREATE TABLE TB_NUMERO_COMANDA (
	ID_SERIAL_COMANDA BIGINT NOT NULL AUTO_INCREMENT,
    ID_EMPRESA INT,
    NUMERO_COMANDA BIGINT,
    PRIMARY KEY(ID_SERIAL_COMANDA),
    KEY IDX_EMPRESA313 (ID_EMPRESA)
);

CREATE TABLE tb_comanda (
ID_COMANDA bigint(20) NOT NULL AUTO_INCREMENT,
NUMERO_COMANDA bigint(20) DEFAULT NULL,
DATA_HORA datetime DEFAULT NULL,
NOME_CLIENTE varchar(120) DEFAULT NULL,
ENDERECO_CLIENTE varchar(200) DEFAULT NULL,
BAIRRO_CLIENTE varchar(150) DEFAULT NULL,
TELEFONE_CLIENTE varchar(20) DEFAULT NULL,
CODIGO_PRODUTO varchar(25) DEFAULT NULL,
QTDE decimal(18,3) DEFAULT NULL,
PRECO_UNITARIO decimal(18,2) DEFAULT NULL,
VALOR_TOTAL decimal(18,2) DEFAULT NULL,
FORMA_PAGTO varchar(30) DEFAULT NULL,
NUMERO_CARTAO varchar(20) DEFAULT NULL,
NOME_CARTAO varchar(100) DEFAULT NULL,
VALIDADE_CARTAO varchar(5) DEFAULT NULL,
COD_SEGURANCA varchar(4) DEFAULT NULL,
RETORNO_COD_AUTORIZACAO decimal(5,0) DEFAULT NULL,
RETORNO_DATA_HORA datetime DEFAULT NULL,
RETORNO_COD_LR varchar(20) DEFAULT NULL,
RETORNO_MENSAGEM varchar(200) DEFAULT NULL,
RETORNO_COD_NSU decimal(5,0) DEFAULT NULL,
RETORNO_TOTAL decimal(18,2) DEFAULT NULL,
ID_USUARIO int(11) DEFAULT NULL,
PAGAMENTO_AUTORIZADO decimal(1,0) DEFAULT NULL,
DESCRICAO_PRODUTO varchar(250) DEFAULT NULL,
RESPOSTA_BIN longtext,
RETORNO_APPROVAL_CODE varchar(40) DEFAULT NULL,
RETORNO_ORDER_ID varchar(30) DEFAULT NULL,
RETORNO_BANDEIRA varchar(50) DEFAULT NULL,
ID_CLIENTE int(11) DEFAULT NULL,
ID_PRODUTO bigint(20) DEFAULT NULL,
ID_OPCIONAL bigint(20) DEFAULT NULL,
ID_EMPRESA INT,
ID_ENDERECO BIGINT,
STATUS_PEDIDO INT,
DATA_HORA_AGENDA DATETIME,
TEMPO_ENTREGA varchar(5),
ORIGEM VARCHAR(30),
PERCENTUAL_ORIGEM NUMERIC(10, 2),
DATA_PAGAMENTO DATETIME,
QTDE_DEVOLVIDA decimal(18,3),
LATITUDE numeric(18, 11),
LONGITUDE numeric(18, 11),
METADE numeric(1),
UM_TERCO numeric(1),
TROCO numeric(18,2),
MOTIVO_DEVOLUCAO varchar(100) DEFAULT NULL,
VALOR_DESCONTO decimal(12,2) DEFAULT NULL,
XML_NOTA longtext,
RESPOSTA_SEFAZ longtext,
NUMERO_NF decimal(18,0) DEFAULT NULL,
SERIE_NF varchar(10) DEFAULT NULL,
CHAVE_ACESSO_NF varchar(50) DEFAULT NULL,
PROTOCOLO_AUTORIZACAO varchar(25) DEFAULT NULL,
CPF varchar(15) DEFAULT NULL,
ID_TRANSPORTE bigint(20) DEFAULT NULL,
INFO_ADICIONAL varchar(3000) DEFAULT NULL,
PDF_DANFE longblob,
PESO decimal(10,3) DEFAULT NULL,
ESPECIE varchar(15) DEFAULT NULL,
NUMERO_PEDIDO_ZE_DELIVERY bigint(20) DEFAULT NULL,
FILA_NFE decimal(10,0) DEFAULT NULL,
PDF_ZE_DELIVERY longblob,
CAIXINHA decimal(12,2) DEFAULT NULL,
IE varchar(15) DEFAULT NULL,
MOTIVO_CANCELAMENTO varchar(500) DEFAULT NULL,
COMENTARIOS_AVALIACAO varchar(1000),
NOTA_AVALIACAO numeric(5,0),
ORDEM_ROTEIRO numeric(10,0),
TEMPO_ATENDIMENTO_ROBO datetime,
TEMPO_ENTREGA_PEDIDO datetime,
PEDIDO_IMPORTADO numeric(1),
NUMERO_PEDIDO_DELIVERY bigint,
ASSINATURA_NFCE longtext,
DATA_AUTORIZACAO_NFCE varchar(20),
NUMERO_PEDIDO_LALAMOVE varchar(40),
NUMERO_PEDIDO_IFOOD varchar(50),
CHAVE_PEDIDO varchar(15),
TIPO_PEDIDO_IFOOD int,
ID_TRIBUTO bigint,
ID_PEDIDO_IFOOD varchar(100),
ITEM_ALTERADO int,
CODIGO_IDENTIFICACAO_IFOOD VARCHAR(30),
ORDER_NUMBER_GOOMER bigint,
ID_PEDIDO_GOOMER bigint,
MESA varchar(5), 
TIPO_ADICIONAL varchar(5), 
NUMERO_PESSOAS int,
NUMERO_VENDA int,
XML_DEVOLUCAO longtext,
NUMERO_NF_DEVOLUCAO bigint,
ORDER_NUMBER_WABIZ bigint,
INTERNAL_KEY_WABIZ varchar(150),
ORDER_NUMBER_RAPPI bigint,
JSON longtext,
DATA_ENTREGA datetime,
REQUEST_ID_FATTORINO varchar(25),
GERAR_DANFE int,
INTERNAL_KEY_ZION varchar(150),
CHAVE_NF_DEVOLUCAO varchar(50),
TEMPO_RETIRADA_LOJA datetime,
TEMPO_MOTOBOY_CAMINHO datetime,
ID_COMANDA_LOCAL BIGINT,
ID_TERMINAL int,
   PRIMARY KEY (ID_COMANDA),
   KEY IDX_COMANDA (NUMERO_COMANDA),
   KEY IDX_DATA_CLIENTE (DATA_HORA,NOME_CLIENTE),
   KEY ID_USUARIO (ID_USUARIO),
   KEY IDX_NUMERO_PEDIDO_DELIVERY (NUMERO_PEDIDO_DELIVERY),
   KEY IDX_EMPRESA_STATUS (ID_EMPRESA, STATUS_PEDIDO),
   KEY IDX_ZE_DELIVERY (NUMERO_PEDIDO_ZE_DELIVERY),
   KEY IDX_FILA_NFE (FILA_NFE),
   KEY IDX_PEDIDO_LALAMOVE (NUMERO_PEDIDO_LALAMOVE),
   key IDX_ORDER_NUMBER_GOOMER (ORDER_NUMBER_GOOMER),
   key IDX_PRODUTO_DATA1 (DESCRICAO_PRODUTO, DATA_HORA),
   key IDX_ORDER_WABIZ (ORDER_NUMBER_WABIZ),
   key IDX_ORDER_NUMBER_RAPPI (ORDER_NUMBER_RAPPI),
   key IDX_PEDIDO_IFOOD (NUMERO_PEDIDO_IFOOD),
   key IDX_ENTREGA (DATA_ENTREGA),
   key IDX_ID_CLIENTE (ID_CLIENTE),
   KEY IDX_WOO (NUMERO_PEDIDO_DELIVERY, INTERNAL_KEY_ZION),
   key IDX_NUMERO_NF_COMANDA (NUMERO_COMANDA),
   CONSTRAINT tb_comanda_ibfk_1 FOREIGN KEY (ID_USUARIO) REFERENCES tb_usuario (ID_USUARIO),
   CONSTRAINT TB_EMPRESA_FK10 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA),
   CONSTRAINT TB_ENDERECO_FK28 FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO_CLIENTE (ID_ENDERECO)
 );

CREATE TABLE tb_pagamento_comanda (
 ID_PAGAMENTO bigint(20) NOT NULL AUTO_INCREMENT,
 NUMERO_COMANDA bigint(20) DEFAULT NULL,
 FORMA_PAGTO varchar(30) DEFAULT NULL,
 NUMERO_CARTAO varchar(100) DEFAULT NULL,
 NOME_CARTAO varchar(100) DEFAULT NULL,
 VALIDADE_CARTAO varchar(7) DEFAULT NULL,
 COD_SEGURANCA varchar(50) DEFAULT NULL,
 RETORNO_COD_AUTORIZACAO decimal(5,0) DEFAULT NULL,
 RETORNO_DATA_HORA datetime DEFAULT NULL,
 RETORNO_COD_LR varchar(20) DEFAULT NULL,
 RETORNO_MENSAGEM varchar(200) DEFAULT NULL,
 RETORNO_COD_NSU decimal(5,0) DEFAULT NULL,
 RETORNO_TOTAL decimal(18,2) DEFAULT NULL,
 PAGAMENTO_AUTORIZADO decimal(1,0) DEFAULT NULL,
 ID_COMANDA bigint(20) DEFAULT NULL,
 VALOR_PAGO decimal(18,2) DEFAULT NULL,
 RESPOSTA_BIN longtext,
 RETORNO_APPROVAL_CODE varchar(40) DEFAULT NULL,
 RETORNO_ORDER_ID varchar(30) DEFAULT NULL,
 RETORNO_BANDEIRA varchar(50) DEFAULT NULL,
 ID_EMPRESA int(11) DEFAULT NULL,
 RETORNO_PAYMENT_ID varchar(60) DEFAULT NULL,
 ORIGEM varchar(30),
 ID_PAGAMENTO_LOCAL BIGINT,
 ID_TERMINAL int,
   PRIMARY KEY (ID_PAGAMENTO),
   KEY IDX_NUMERO_COMANDA (NUMERO_COMANDA),
   KEY ID_COMANDA (ID_COMANDA),
   KEY IDX_RETORNO_DATA_HORA (RETORNO_DATA_HORA),
   KEY IDX_FORMA_ORIGEM_DATA (FORMA_PAGTO, ORIGEM, RETORNO_DATA_HORA)
 );

CREATE TABLE tb_plano_conta (
    ID_PLANO varchar(10) NOT NULL,
    DESCRICAO_PLANO VARCHAR(100),
    CREDITO_DEBITO INT,
    PAI_PLANO varchar(10),
    PRIMARY KEY(ID_PLANO)
 );
 
 CREATE TABLE tb_financeiro (
    ID_FINANCEIRO BIGINT NOT NULL AUTO_INCREMENT,
    CREDITO_DEBITO INT,
    DATA_LANCAMENTO DATETIME,
    DATA_VENCIMENTO DATETIME,
    DATA_PAGAMENTO DATETIME,
    NUMERO_SEQ_NF_SAIDA bigint,
    NUMERO_SEQ_NF_ENTRADA bigint,
    VALOR DECIMAL(18,2),
    VALOR_DESCONTO DECIMAL(18,2),
    VALOR_ACRESCIMO DECIMAL(18,2),
    VALOR_TOTAL DECIMAL(18,2),
    HISTORICO varchar(250),
    ID_EMPRESA INT,
    ID_PLANO varchar(10),
    NUMERO_COMANDA bigint,
    ID_FINANCEIRO_LOCAL BIGINT,
    ID_TERMINAL int,
    PRIMARY KEY(ID_FINANCEIRO),
    KEY IDX_LANCAMENTO (ID_EMPRESA, DATA_LANCAMENTO),
    KEY IDX_VENCIMENTO (ID_EMPRESA, DATA_VENCIMENTO),
    KEY IDX_PAGAMENTO (ID_EMPRESA, DATA_PAGAMENTO),
    CONSTRAINT TB_EMPRESA_FK31 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA) 
 );

CREATE TABLE tb_produto_opcional (
    ID_OPCIONAL bigint(20) AUTO_INCREMENT NOT NULL,
    ID_PRODUTO 	bigint(20),
    DESCRICAO_OPCIONAL varchar(150),
    VALOR_OPCIONAL numeric(18,2),
    FOTO_PRODUTO longblob,
    ARQUIVO_FOTO varchar(200),
    PRIMARY KEY(ID_OPCIONAL),
    KEY IDX_PRODUTOX1 (ID_PRODUTO, DESCRICAO_OPCIONAL),
    CONSTRAINT TB_PRODUTO_FK46 FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO)
);

CREATE TABLE tb_cliente_loja (
    ID_CLIENTE_LOJA bigint AUTO_INCREMENT NOT NULL,
    ID_CLIENTE int,
    ID_ENDERECO bigint,
    PRIMARY KEY(ID_CLIENTE_LOJA),
    KEY IDX_CL1 (ID_CLIENTE),
    KEY IDX_CL2 (ID_ENDERECO),
    KEY IDX_CL3 (ID_CLIENTE, ID_ENDERECO),
    CONSTRAINT TB_CLIENTE_LOJA_FK1 FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE),
    CONSTRAINT TB_CLIENTE_LOJA_FK2 FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO_CLIENTE (ID_ENDERECO)
);

create table tb_campanha (
    ID_CAMPANHA bigint not null auto_increment,
    ID_CLIENTE int,
    DATA_CAMPANHA datetime,
    TEXTO_CAMPANHA varchar(600),
    ID_EMPRESA int,
    PRIMARY KEY(ID_CAMPANHA),
    KEY IDX_CLC1 (ID_CLIENTE),
    CONSTRAINT TB_CAMPANHA_FKC1 FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE),
    CONSTRAINT TB_CAMPANHA_FKE1 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA)
);

create table contatos (
    ID_CLIENTE bigint not null,
    NICKNAME varchar(40),
    WHATS varchar(25),
    PRIMARY KEY(ID_CLIENTE)
);

create table tb_processo_negocio (
    ID_FASE BIGINT auto_increment not null,
    DESCRICAO_FASE varchar(100),
    ITERACAO_CLIENTE varchar(500),
    RESPOSTA_ROBO varchar(500),
    ID_EMPRESA int,
    primary key(ID_FASE),
    KEY IDX_EMPR1 (ID_EMPRESA),
    CONSTRAINT TB_EMPRESA_FKE5 FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA (ID_EMPRESA)
);

create table tb_atendimento_robo(
    ID_ATENDIMENTO bigint auto_increment not null,
    ID_FASE bigint,
    DATA_HORA datetime,
    ITERACAO_CLIENTE varchar(500),
    RESPOSTA_ROBO varchar(500),
    primary key(ID_ATENDIMENTO),
    KEY IDX_AR1 (DATA_HORA),
    KEY IDX_AR2 (ID_FASE),
    CONSTRAINT TB_PROCESSO_NEGOCIO_FKPN1 FOREIGN KEY (ID_FASE) REFERENCES tb_processo_negocio (ID_FASE)
);

create table tb_forma_pagto (
	ID_FORMA bigint not null auto_increment,
	DESCRICAO_FORMA varchar(30),
    PAGTO_FUTURO int,
    VALE_FUNCIONARIO int,
    VALOR_DIA NUMERIC(12, 2),
    TAXA_PAGAMENTO numeric(12, 2),
    DIAS_PAGAMENTO int,
	primary key(ID_FORMA)
);

CREATE TABLE tb_abertura_caixa (
 ID_ABERTURA bigint(20) NOT NULL AUTO_INCREMENT,
 ID_EMPRESA bigint(20) DEFAULT NULL,
 DATA_ABERTURA datetime DEFAULT NULL,
 VALOR_ABERTURA decimal(18,2) DEFAULT NULL,
 VALOR_SANGRIA decimal(18,2) DEFAULT NULL,
 VALOR_FECHAMENTO decimal(18,2) DEFAULT NULL,
 VALOR_FECHAMENTO_DEBITO decimal(18,2) DEFAULT NULL,
 VALOR_FECHAMENTO_CREDITO decimal(18,2) DEFAULT NULL,
 ID_USUARIO int(11) DEFAULT NULL,
 DATA_FECHAMENTO datetime,
 IMPRESSAO int,
 ID_ABERTURA_LOCAL bigint,
 ID_TERMINAL int,
 PRIMARY KEY (ID_ABERTURA),
 KEY IDX_EMPRESA_DATA_ABERTURA (ID_EMPRESA,DATA_ABERTURA),
 KEY IDX_IMPRESSAO_RESUMO (IMPRESSAO)
 ); 

CREATE TABLE tb_fila_comanda (
 ID_FILA bigint(20) NOT NULL AUTO_INCREMENT,
 NUMERO_COMANDA bigint(20) DEFAULT NULL,
 PROCESSADO decimal(1,0) DEFAULT NULL,
 PRIMARY KEY (ID_FILA),
 KEY IDX_FILA_PROCESSADO (PROCESSADO),
 KEY IDX_FILA_COMANDA1 (NUMERO_COMANDA)
);

CREATE TABLE tb_fila_roteiro (
 ID_FILA bigint(20) NOT NULL AUTO_INCREMENT,
 NUMERO_COMANDA bigint(20) DEFAULT NULL,
 NUMERO_DEMANDA bigint(20) DEFAULT NULL,
 PROCESSADO decimal(1,0) DEFAULT NULL,
 ORIGEM varchar(15),
 PRIMARY KEY (ID_FILA),
 KEY IDX_FILA_PROCESSADO1 (PROCESSADO),
 KEY IDX_FILA_COMANDA2 (NUMERO_COMANDA)
);

CREATE TABLE tb_reforco_caixa (
 ID_REFORCO bigint(20) NOT NULL AUTO_INCREMENT,
 DATA_REFORCO datetime DEFAULT NULL,
 DESCRICAO_REFORCO varchar(120) DEFAULT NULL,
 ID_USUARIO int(11) DEFAULT NULL,
 VALOR_REFORCO decimal(18,2) DEFAULT NULL,
 ID_REFORCO_LOCAL bigint,
 ID_TERMINAL int,
 ID_ABERTURA bigint,
 PRIMARY KEY (ID_REFORCO)
 );

CREATE TABLE tb_sangria (
 ID_SANGRIA bigint(20) NOT NULL AUTO_INCREMENT,
 DATA_SANGRIA datetime DEFAULT NULL,
 DESCRICAO_SANGRIA varchar(120) DEFAULT NULL,
 ID_USUARIO int(11) DEFAULT NULL,
 VALOR_SANGRIA decimal(18,2) DEFAULT NULL,
 ID_SANGRIA_LOCAL bigint,
 ID_TERMINAL int,
 ID_ABERTURA bigint,
 PRIMARY KEY (ID_SANGRIA),
 KEY IDX_DATA_SANGRIA (DATA_SANGRIA)
 );

CREATE TABLE tb_transporte (
 ID_TRANSPORTE bigint(20) NOT NULL AUTO_INCREMENT,
 NOME_TRANSPORTE varchar(80) DEFAULT NULL,
 CNPJ varchar(20) DEFAULT NULL,
 IE varchar(15) DEFAULT NULL,
 ENDERECO varchar(80) DEFAULT NULL,
 CIDADE varchar(100) DEFAULT NULL,
 UF varchar(2) DEFAULT NULL,
 PLACA varchar(15) DEFAULT NULL,
 EMAIL varchar(100),
 ID_FATTORINO int,
 PRIMARY KEY (ID_TRANSPORTE)
);

create table tb_versao_robo (
ID_VERSAO int not null auto_increment, 
VERSAO varchar(20),
VERSAO_SAIDERA varchar(20),
CLASS_PRODUCT_DESCRIPTION varchar(35),
CLASS_PRODUCT_QTY varchar(35),
CLASS_PRODUCT_PRICE varchar(35),
primary key(ID_VERSAO)
);

create table tb_log (
ID_LOG bigint not null auto_increment,
DATA_LOG datetime,
ID_USUARIO int,
TABELA varchar(50),
CAMPO varchar(100),
ANTIGO_VALOR varchar(500),
NOVO_VALOR varchar(500),
KEY IDX_DATA_LOG (DATA_LOG),
primary key(ID_LOG)
);

create table tb_municipio (
ID_IBGE bigint auto_increment not null,
ID_UF numeric(10),
ID_MUNICIPIO numeric(10),
NOME_MUNICIPIO varchar(100),
SIGLA_UF varchar(2),
KEY IDX_NOME_MUNICIPIO (NOME_MUNICIPIO),
primary key(ID_IBGE)
);

create table tb_nota_entrada (
ID_NF bigint auto_increment not null,
NUMERO_NF bigint,
DATA_EMISSAO datetime,
NOME_EMITENTE varchar(180),
DESCRICAO_PRODUTO varchar(180),
XML_NOTA longtext,
PRECO_UNITARIO numeric(18,11),
QTDE_ITEM numeric(18,3),
ID_PRODUTO bigint,
CNPJ_FORNECEDOR varchar(20),
QTDE_CONVERSOR numeric(18,3),
ID_EMPRESA int,
DATA_VALIDADE datetime,
ID_MATERIA_PRIMA bigint,
NOTA_CONFIRMADA int,
key IDX_CNPJ_PRODUTO_DATA_DESC (CNPJ_FORNECEDOR, ID_PRODUTO, DATA_EMISSAO DESC),
key IDX_EMISSAO_NF (DATA_EMISSAO),
key IDX_NUMERO_NF1 (NUMERO_NF),
key IDX_ID_PRODUTO_COMPRA (ID_PRODUTO),
primary key(ID_NF)
);

create table tb_fila_nfce (
ID_FILA bigint auto_increment not null,
DATA_HORA datetime,
LOJA varchar(150),
PROCESSADO numeric(1),
NUMERO_COMANDA bigint,
PEDIDO longtext,
primary key (ID_FILA),
key(PROCESSADO, LOJA),
key(NUMERO_COMANDA)
);

CREATE TABLE tb_fila_ze (
 ID_FILA bigint(20) NOT NULL AUTO_INCREMENT,
 NUMERO_ZE bigint(20) DEFAULT NULL,
 PROCESSADO decimal(1,0) DEFAULT NULL,
 PRIMARY KEY (ID_FILA),
 KEY IDX_FILA_PROCESSADO3 (PROCESSADO),
 KEY IDX_FILA_COMANDA3 (NUMERO_ZE)
);

create table tb_fila_etiqueta (
ID_FILA bigint auto_increment not null,
ID_PRODUTO bigint,
QTDE int,
PRECO numeric(18,2),
PROCESSADO INT,
INDEX IDX_PROCESSADO_ETIQUETA (PROCESSADO),
PRIMARY KEY(ID_FILA)
);

create table tb_atendimento_comanda (
ID_ATENDIMENTO bigint auto_increment not null,
NUMERO_COMANDA_ATENDIMENTO bigint,
ID_PRODUTO bigint,
QTDE numeric(12,3),
PRECO numeric(18,2),
NUMERO_COMANDA bigint,
FECHADO int,
DATA_HORA datetime,
ID_TRIBUTO bigint,
MESA varchar(5),
OBS_ITEM varchar(200),
IMPRESSAO int,
AGRUPADOR int,
IMPRESSAO_PRECONTA int,
DESCONTO numeric(12,2),
ADICIONAL numeric(12,2),
DESCRICAO_PRODUTO varchar(180),
QTDE_IMPRESSAO int,
ID_ATENDIMENTO_LOCAL bigint,
ID_TERMINAL int,
NOME_MESA varchar(50),
INDEX IDX_COMANDA1 (NUMERO_COMANDA), INDEX IDX_COMANDA_FECHADA (FECHADO),
INDEX IDX_IMPRESSAO (IMPRESSAO), primary key (ID_ATENDIMENTO));

create table tb_log_ifood (
ID_LOG bigint not null auto_increment,
DATA_LOG datetime,
EVENTO_IFOOD varchar(50),
ACAO_ZION varchar(100),
INDEX IDX_DATA1_LOG (DATA_LOG),
primary key (ID_LOG)
);

create table tb_combo_produto (
ID_PRODUTO bigint not null,
ID_PRODUTO_COMBO bigint not null,
QTDE_COMBO numeric(18,3),
PRECO_COMBO numeric(18,2),
primary key(ID_PRODUTO, ID_PRODUTO_COMBO)
);

create table tb_log_zion (
ID_LOG bigint auto_increment not null,
DATA_LOG datetime,
ID_USUARIO int,
ERRO_LOG longtext,
primary key (ID_LOG),
key idx_zion_data_log (DATA_LOG)
);

create table tb_cfop (
    CFOP varchar(5) not null,
    DESCRICAO_CFOP varchar(150),
    VENDA int,
    DEVOLUCAO int,
    primary key(CFOP)
);

create table tb_tributo (
ID_TRIBUTO bigint auto_increment not null,
NCM varchar(10),
UF_DESTINO varchar(2),
CFOP varchar(5),
CST varchar(5),
ALIQ_ICMS numeric(12,2),
ALIQ_INTERNA_ICMS numeric(12, 2),
MODO_BASE_CALCULO_ICMS_ST varchar(2),
IVA numeric(12, 2),
CST_IPI varchar(3),
ALIQ_IPI numeric(12,2),
CST_PIS varchar(3),
ALIQ_PIS numeric(12, 2),
CST_COFINS varchar(3),
ALIQ_COFINS numeric(12, 2),
NOME_OPERACAO varchar(50),
CEST varchar(15),
PERCENTUAL_RED_BASE_ICMS numeric(12,2),
CODIGO_GENERO varchar(30),
ID_EMPRESA bigint,
PERCENTUAL_FCP numeric(10,2),
primary key (ID_TRIBUTO),
key idx_ncm_uf (NCM, UF_DESTINO)
);

create table tb_emitente_nf_origem (
 ID_ORIGEM bigint NOT NULL auto_increment,
 ID_EMPRESA bigint,
 ORIGEM varchar(30),
 primary key(ID_ORIGEM)
);

create table tb_tributo_produto (
 ID_TRIBUTO_PRODUTO bigint NOT NULL auto_increment,
 ID_PRODUTO bigint,
 ID_TRIBUTO bigint,
 ID_EMPRESA bigint,
 primary key(ID_TRIBUTO_PRODUTO)
);

create table tb_conciliacao_rede (
ID_CONCILIACAO bigint not null auto_increment,
DATA_HORA datetime,
VALOR numeric(18,2),
NUMERO_COMANDA bigint,
NSU varchar(25),
BANDEIRA varchar(25),
FORMA_PAGTO varchar(25),
key idx_data_conciliacao (DATA_HORA),
primary key(ID_CONCILIACAO));

create table tb_monitor_loja (
ID_MONITOR bigint not null auto_increment,
DATA_HORA datetime,
CNPJ varchar(20),
SAT_OK int,
INTERNET_ZION_OK int,
IMPRESSORA_OK int,
SEFAZ_OK int,
DATA_ULTIMO_PEDIDO datetime,
DATA_ULTIMA_NF datetime,
ULTIMO_ERRO_CFE varchar(500),
key idx_data_monitor (DATA_HORA),
primary key(ID_MONITOR));

create table tb_cardapio_digital (
ID_CARDAPIO bigint auto_increment not null,
ID_PRODUTO bigint,
DESCRICAO_CARDAPIO varchar(300),
PRECO numeric(12,2),
FOTO_PRODUTO longblob,
ITEM_ATIVO int,
index IDX_PRODUTO_CARDAPIO (ID_PRODUTO),
primary key (ID_CARDAPIO)
);

create table tb_nsu_nfe (
	ID_NSU bigint not null auto_increment,
    NSU int,
	CHAVE_ACESSO varchar(55),
	EMISSAO_PROPRIA int,
    XML_CONTENT longtext,
    IS_NFE int,
	EMITENTE_CNPJ varchar(20),
    EMITENTE_RAZAO_SOCIAL varchar(180),
    NUMERO_NFE bigint,
    DATA_EMISSAO datetime,
    VALOR_NFE decimal(12,2),
	SITUACAO int,
	DESCRICAO varchar(20),
    primary key(ID_NSU)
);

create table tb_xml_nsu (
	ID_XML bigint auto_increment not null,
    ID_NSU bigint,
	INCLUSAO datetime,
	EMISSAO_PROPRIA int,
	CHAVE_ACESSO varchar(55),
	XML_CONTENT longtext,
    INDEX IDX_NSU1 (ID_NSU),
    primary key(ID_XML)
);

create table tb_codigo_barras_produto (
ID_BARRAS bigint not null auto_increment,
ID_PRODUTO bigint,
CODIGO_BARRAS_PRODUTO varchar(30),
KEY IDX_COD_BARRAS_PRODUTO (CODIGO_BARRAS_PRODUTO),
primary key (ID_BARRAS)
);

CREATE TABLE tb_pedido (
NUMERO_PEDIDO bigint NOT NULL AUTO_INCREMENT,
DATA_HORA datetime DEFAULT NULL,
DATA_ENTREGA datetime,
DATA_HORA_AGENDA DATETIME,
TEMPO_ENTREGA varchar(5),
TEMPO_RETIRADA_LOJA datetime,
TEMPO_MOTOBOY_CAMINHO datetime,

ID_CLIENTE int,
ID_ENDERECO BIGINT,

CPF varchar(15) DEFAULT NULL,
IE varchar(15) DEFAULT NULL,
NOME_CLIENTE varchar(120) DEFAULT NULL,
ENDERECO_CLIENTE varchar(200) DEFAULT NULL,
BAIRRO_CLIENTE varchar(150) DEFAULT NULL,
TELEFONE_CLIENTE varchar(20) DEFAULT NULL,
LATITUDE numeric(18, 11),
LONGITUDE numeric(18, 11),

ORIGEM VARCHAR(30),
ID_CAIXA bigint,
STATUS_PEDIDO INT,

NUMERO_PESSOAS int,
NUMERO_VENDA int,
TIPO_ADICIONAL varchar(20), 

TOTAL_PRODUTOS numeric(12,2),
TROCO numeric(12,2),
DESCONTO numeric(12,2),
ADICIONAL numeric(12,2),
TAXA_ENTREGA numeric(12,2),
TOTAL_PEDIDO numeric(12,2),

MOTIVO_DEVOLUCAO varchar(100) DEFAULT NULL,
ID_TRANSPORTE bigint,
INFO_ADICIONAL varchar(3000) DEFAULT NULL,

NUMERO_PEDIDO_ZE_DELIVERY bigint(20) DEFAULT NULL,
NUMERO_PEDIDO_DELIVERY bigint,
NUMERO_PEDIDO_LALAMOVE varchar(40),
NUMERO_PEDIDO_IFOOD varchar(50),
ID_PEDIDO_IFOOD varchar(100),
TIPO_PEDIDO_IFOOD int,
CODIGO_IDENTIFICACAO_IFOOD VARCHAR(30),
ORDER_NUMBER_GOOMER bigint,
ID_PEDIDO_GOOMER bigint,
ORDER_NUMBER_WABIZ bigint,
INTERNAL_KEY_WABIZ varchar(150),
ORDER_NUMBER_RAPPI bigint,
REQUEST_ID_FATTORINO varchar(25),
INTERNAL_KEY_ZION varchar(150),

MOTIVO_CANCELAMENTO varchar(500) DEFAULT NULL,
COMENTARIOS_AVALIACAO varchar(1000),
NOTA_AVALIACAO numeric(5,0),
ORDEM_ROTEIRO numeric(10,0),
TEMPO_ATENDIMENTO_ROBO datetime,
TEMPO_ENTREGA_PEDIDO datetime,

ID_PEDIDO_LOCAL BIGINT,
ID_TERMINAL int,

   PRIMARY KEY (NUMERO_PEDIDO),
   KEY IDX_PEDIDO (NUMERO_PEDIDO),
   KEY IDX_DATA_CLIENTE1 (ID_CLIENTE, DATA_HORA),
   KEY IDX_DATAX (DATA_HORA),
   KEY IDX_CAIXA_PEDIDO (ID_CAIXA),
   KEY IDX_NUMERO_PEDIDO_DELIVERY1 (NUMERO_PEDIDO_DELIVERY),
   KEY IDX_STATUS_PEDIDO (STATUS_PEDIDO),
   KEY IDX_ZE_DELIVERY1 (NUMERO_PEDIDO_ZE_DELIVERY),
   KEY IDX_PEDIDO_LALAMOVE1 (NUMERO_PEDIDO_LALAMOVE),
   key IDX_ORDER_NUMBER_GOOMER1 (ORDER_NUMBER_GOOMER),
   key IDX_ORDER_WABIZ1 (ORDER_NUMBER_WABIZ),
   key IDX_ORDER_NUMBER_RAPPI1 (ORDER_NUMBER_RAPPI),
   key IDX_PEDIDO_IFOOD1 (NUMERO_PEDIDO_IFOOD),
   key IDX_ENTREGA1 (DATA_ENTREGA),
   key IDX_ID_CLIENTE1 (ID_CLIENTE),
   KEY IDX_WOO1 (NUMERO_PEDIDO_DELIVERY, INTERNAL_KEY_ZION),
   key IDX_CLIENTEX (ID_CLIENTE),
   key IDX_PEDIDO_LOCAL (ID_PEDIDO_LOCAL, ID_TERMINAL),
   key IDX_TRANSPORTEX (ID_TRANSPORTE),
   key IDX_STATUS_DATA (STATUS_PEDIDO, DATA_HORA),
   
   CONSTRAINT tb_caixa_ibfk_1 FOREIGN KEY (ID_CAIXA) REFERENCES tb_abertura_caixa (ID_ABERTURA),
   CONSTRAINT TB_CLIENTE_FK29 FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE),
   CONSTRAINT TB_ENDERECO_FK29 FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO_CLIENTE (ID_ENDERECO),
   CONSTRAINT TB_TRANSPORTE_FK28 FOREIGN KEY (ID_TRANSPORTE) REFERENCES TB_TRANSPORTE (ID_TRANSPORTE)
 );

CREATE TABLE tb_item_pedido (
NUMERO_ITEM bigint NOT NULL AUTO_INCREMENT,
NUMERO_PEDIDO bigint,
ID_PRODUTO bigint,
CODIGO_PRODUTO varchar(25),
QTDE numeric(12,3) DEFAULT NULL,
PRECO_UNITARIO numeric(12,2) DEFAULT NULL,
VALOR_TOTAL numeric(12,2) DEFAULT NULL,
ID_TRIBUTO bigint,
OBS_ITEM varchar(200),
ID_ITEM_LOCAL BIGINT,
ID_TERMINAL int,
   PRIMARY KEY (NUMERO_ITEM),
   KEY IDX_PEDIDO1 (NUMERO_PEDIDO),
   KEY IDX_PRODUTO_ITEM (ID_PRODUTO),
   KEY IDX_ITEM_PEDIDO_LOCAL (ID_ITEM_LOCAL, ID_TERMINAL),
   
   CONSTRAINT tb_pedido_ibfk_2 FOREIGN KEY (NUMERO_PEDIDO) REFERENCES tb_pedido (NUMERO_PEDIDO),
   CONSTRAINT TB_PRODUTO_FK10 FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
   CONSTRAINT TB_TRIBUTO_FK10 FOREIGN KEY (ID_TRIBUTO) REFERENCES TB_TRIBUTO (ID_TRIBUTO)
);

create table tb_pedido_nfe (
ID_PEDIDO_NFE bigint NOT NULL AUTO_INCREMENT,
NUMERO_PEDIDO bigint,
XML_NOTA longtext,
RESPOSTA_SEFAZ longtext,
NUMERO_NF decimal(18,0) DEFAULT NULL,
SERIE_NF varchar(10) DEFAULT NULL,
CHAVE_ACESSO_NF varchar(50) DEFAULT NULL,
PROTOCOLO_AUTORIZACAO varchar(25) DEFAULT NULL,
PROCESSADO int DEFAULT NULL,
ASSINATURA_NFCE longtext,
DATA_AUTORIZACAO_NFCE varchar(20),
CHAVE_PEDIDO varchar(15),
XML_DEVOLUCAO longtext,
NUMERO_NF_DEVOLUCAO bigint,
GERAR_DANFE int,
ID_EMPRESA int,
CHAVE_NF_DEVOLUCAO varchar(50),
ID_PEDIDO_NFE_LOCAL BIGINT,
ID_TERMINAL int,

PRIMARY KEY (ID_PEDIDO_NFE),
KEY IDX_PEDIDO8 (NUMERO_PEDIDO),
KEY IDX_PROCESSADO1 (PROCESSADO),
KEY IDX_NUMERO_NF1 (NUMERO_NF),
KEY IDX_PEDIDO_NFE_LOCAL (ID_PEDIDO_NFE_LOCAL, ID_TERMINAL),
KEY IDX_PEDIDO_PROCESSADO (NUMERO_PEDIDO, PROCESSADO),

CONSTRAINT tb_pedido_ibfk_8 FOREIGN KEY (NUMERO_PEDIDO) REFERENCES tb_pedido (NUMERO_PEDIDO)
);

create table tb_pedido_pagamento(
 ID_PAGAMENTO bigint NOT NULL AUTO_INCREMENT,
 NUMERO_PEDIDO bigint,
 DATA_HORA datetime,
 FORMA_PAGTO varchar(30) DEFAULT NULL,
 VALOR_PAGO decimal(18,2) DEFAULT NULL,
 ID_CAIXA bigint,
 ORIGEM varchar(30),
 ID_PAGAMENTO_LOCAL BIGINT,
 ID_TERMINAL int,
 CODIGO_NSU varchar(100),
 VALOR_PAGO_STONE decimal(12,2), 
 DATA_AUTORIZACAO datetime, 
 BANDEIRA varchar(50),

PRIMARY KEY (ID_PAGAMENTO),
   
   KEY IDX_NUMERO_PEDIDO6 (NUMERO_PEDIDO),
   KEY IDX_DATA_HORA6 (DATA_HORA),
   KEY IDX_FORMA_DATA6 (FORMA_PAGTO, DATA_HORA),
   KEY IDX_PEDIDO_PAGAMENTO_LOCAL (ID_PAGAMENTO_LOCAL, ID_TERMINAL),
   KEY IDX_CAIXA_ORIGEM3 (ID_CAIXA, ORIGEM),

   CONSTRAINT tb_pedido_ibfk_6 FOREIGN KEY (NUMERO_PEDIDO) REFERENCES tb_pedido (NUMERO_PEDIDO),
   CONSTRAINT tb_caixa_ibfk_3 FOREIGN KEY (ID_CAIXA) REFERENCES tb_abertura_caixa (ID_ABERTURA)
);

create table tb_response_stone(
 ID_STONE varchar(50) not null,
 JSON_STONE longtext,
 PRIMARY KEY (ID_STONE)
 );

create table tb_maquina_stone(
 ID_STONE bigint NOT NULL AUTO_INCREMENT,
 SERIAL_NUMBER varchar(50),
 NOME_MAQUINA varchar(50),
 ID_CONTA varchar(50),
 CHAVE_PUBLICA varchar(100),
 PRIMARY KEY (ID_STONE)
);

create table if not exists tb_mesa (
    ID_MESA bigint not null AUTO_INCREMENT,
    NUMERO_MESA varchar(10),
    NOME_MESA varchar(30),
    MESA_FECHADA int,
    NUMERO_PEDIDO bigint,

    PRIMARY KEY (ID_MESA),
    KEY IDX_MESA18 (NUMERO_MESA, MESA_FECHADA),
    KEY IDX_NUMERO_PEDIDO18 (NUMERO_PEDIDO)
);

insert into tb_tributo (NCM, UF_DESTINO, CFOP, CST, ALIQ_ICMS, ALIQ_INTERNA_ICMS, MODO_BASE_CALCULO_ICMS_ST, IVA, CST_IPI, ALIQ_IPI, CST_PIS, ALIQ_PIS, CST_COFINS, ALIQ_COFINS, NOME_OPERACAO, ID_EMPRESA)
values('22030000', 'SP', '5405', '0500', 0, 0, '0', 0, '53', 0, '04', 0, '04', 0, 'CERVEJA / REFRI', 1);

INSERT into tb_empresa (NOME_FANTASIA, RAZAO_SOCIAL, CNPJ, IE, ENDERECO, CEP, CIDADE, UF, TELEFONE, WHATSAPP, EMAIL, EMPRESA_ATIVA, SENHA,
LATITUDE, LONGITUDE, HORA_INICIAL, HORA_FINAL, CONTATO, NUMERO_NF, SERIE_NF, NOME_CERTIFICADO, VALIDADE_CERTIFICADO, SERIAL_PROTOCOLO,
BAIRRO) values('ZION PDV', 'ZION PDV', '02.967.782/0001-68', 'ISENTO', 'AV. AGUA FRIA, 747', '03131-010', 'SÃO PAULO', 'SP', '11992640322', '11992640322', 'caiorodro@gmail.com', 1, '',
0, 0, '12:00', '00:00', 'Caio', 0, '', '', null, '', 'AGUA FRIA');

insert into tb_usuario (EMAIL_USUARIO, SENHA_USUARIO, NOME_USUARIO, USUARIO_ATIVO, TIPO_USUARIO, ID_EMPRESA, ACESSO_FECHAMENTO, TELA_INICIAL, CAIXA_DELIVERY, USUARIO_CAIXA) 
values('admin', 'gQ+ewLK4pAA=', 'Admin', 1, 1, 1, 1, 3, 1, 1);

INSERT INTO tb_forma_pagto (DESCRICAO_FORMA) values('CREDITO');
INSERT INTO tb_forma_pagto (DESCRICAO_FORMA) values('DEBITO');
INSERT INTO tb_forma_pagto (DESCRICAO_FORMA) values('DINHEIRO');
INSERT INTO tb_forma_pagto (DESCRICAO_FORMA) values('ONLINE');
INSERT INTO tb_forma_pagto (DESCRICAO_FORMA) values('PIX');
INSERT INTO tb_forma_pagto (DESCRICAO_FORMA) values('PIX-ONLINE');
INSERT INTO tb_forma_pagto (DESCRICAO_FORMA) values('PAG ONLINE - NUBANK');

INSERT INTO tb_transporte (NOME_TRANSPORTE, CNPJ, IE, ENDERECO, CIDADE, UF, PLACA, EMAIL)
values('TRANSPORTE PROPRIO', 'ISENTO', 'ISENTO', 'ISENTO', 'SAO PAULO', 'SP', 'DDD1111', 'contato@empresacom.br');

insert into tb_municipio (ID_UF, ID_MUNICIPIO, NOME_MUNICIPIO, SIGLA_UF) values(35, 50308, 'SAO PAULO', 'SP');

insert into tb_familia_produto (descricao_familia, id_empresa, icone) values('DIVERSOS', 1, '');
 
insert into tb_produto (CODIGO_PRODUTO, DESCRICAO_PRODUTO, PRECO_VENDA, ID_FAMILIA, ID_EMPRESA, FOTO_PRODUTO, 
PRODUTO_ATIVO, PRECO_CUSTO, ARQUIVO_FOTO, ORDEM_RELEVANCIA, NCM, CODIGO_ZE_DELIVERY, FOTO2_PRODUTO, ARQUIVO2_FOTO)
values('TXENTREGA', 'TAXA DE ENTREGA', 0, 1, 1, null, 1, 0, '', 0, '', 0, null, '');

insert into tb_cliente (NOME_CLIENTE, ENDERECO_CLIENTE, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, BAIRRO_CLIENTE,
CEP_CLIENTE, MUNICIPIO_CLIENTE, UF_CLIENTE, TELEFONE_CLIENTE, EMAIL_CLIENTE, ID_EMPRESA, SENHA_CLIENTE, NICKNAME, METADE, UM_TERCO,
CPF, IE, TAXA_ENTREGA)
values('CONSUMIDOR FINAL', 'ISENTO', '', '', 'ISENTO', '', '', '', '11', 'consumidorfinal@gmail.com', 1, '', '', 1, 1, 'ISENTO', 'ISENTO', 0);

insert into tb_endereco_cliente (ID_CLIENTE, ENDERECO, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, BAIRRO, CEP, MUNICIPIO, UF, ID_EMPRESA, LATITUDE, LONGITUDE)
select ID_CLIENTE, ENDERECO_CLIENTE, NUMERO_ENDERECO, COMPLEMENTO_ENDERECO, BAIRRO_CLIENTE, CEP_CLIENTE, MUNICIPIO_CLIENTE, UF_CLIENTE, 1, 0, 0 from tb_cliente where ID_CLIENTE > 1;
